<?php


namespace Iugu\Models;


use Illuminate\Database\ConnectionResolverInterface as Resolver;
use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    public static function setConnectionResolver(Resolver $resolver)
    {
        parent::setConnectionResolver($resolver); // TODO: Change the autogenerated stub
    }

}
